{"uuid": "172ff44b-829e-4cbc-970b-4fe59ba291b3", "children": ["9a4661cf-6706-4784-961d-fe4094a5e914", "c74ded47-1371-4d81-ad3f-b43c20eab954"], "befores": [{"name": "_xunit_setup_class_fixture_TestUserSettings", "status": "passed", "start": 1690337434761, "stop": 1690337438923}], "afters": [{"name": "_xunit_setup_class_fixture_TestUserSettings::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50377): Max retries exceeded with url: /session/f8f3ecffcd857b6194bd2083960c5673/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106c4c150>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/_pytest/python.py\", line 857, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/_pytest/python.py\", line 774, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/pauliukevi4i/Stotska_final_project/user_settings_tests.py\", line 454, in teardown_class\n    self.login_page.get_sign_in_button().click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pauliukevi4i/Stotska_final_project/pages/login_page.py\", line 24, in get_sign_in_button\n    self._sign_in_button = Button(self._driver.find_element(By.XPATH, \"//button[text()='Sign In']\"))\n                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 740, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/urllib3/_request_methods.py\", line 118, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/urllib3/_request_methods.py\", line 217, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/Users/pauliukevi4i/Stotska_final_project/venv/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1690337475993, "stop": 1690337481014}], "start": 1690337434761, "stop": 1690337481014}